### ISSUE TITLE
Make project more contributor friendly

### ISSUE THREAD

**Issue by beschio** [MagmaGuy/EliteMobs#1]
Hey!

Cool project and nice that it's open source! However, I can't help but feel the project/repository could benefit from a few changes that would make it easier for other developers to help/contribute to it.

The main points I'd like to see improved are as follows:
* Add a `LICENSE` file
* Add a `README.md` file containing information the project 
* Add a `.gitignore` file depicting which files should be kept out of git
* Add a `CONTRIBUTING.md` file containing information about compiling/developing the project. (Example: Since the project uses NMS, explain that running BuildTools is required)
* Implement a build/dependency management system (such as [Maven](https://maven.apache.org/) or [Gradle](https://gradle.org/))
* Add documentation to the project as well as information about adding new mobs/powers
* Remove files that doesn't need to be in git (things like `EliteMobs.iml`, `.idea/`, `META-INF/` & `out/` are all unnecessary I feel)

Let me know what you think and please let me know if you'd like any help reaching any of these goals.

Thanks.

**Comment by MagmaGuy** [comment]
Yeah, I am aware that the github page is a complete mess, but I have very limited interest in having other people contribute to it.

**Comment by beschio** [comment]
Fair enough. So I can assume none of the above requests will be fulfilled?

**Comment by MagmaGuy** [comment]
I see it as a nice aesthetic improvement but not a priority. Short of a large demand for this to be done, it will take the backseat to a fairly long planned feature list.

**Comment by beschio** [comment]
While I agree that many of the things are purely nice-to-have, things like a build/dependency management system would prove really useful. Although if you really don't want people to contribute I guess it might be irrelevant.

Your choice. Thanks for your time.
