### ISSUE TITLE
！Items floating around elitemob will be collected by hopper after it is killed

### ISSUE THREAD

**Issue by AdminHcat** [MagmaGuy/EliteMobs#100]
Items floating around elitemob will be collected by hopper after it is killed

![image](https://user-images.githubusercontent.com/50044729/152631213-8d2da0ec-adfc-4078-b623-bf81cc623f62.png)

**Comment by MagmaGuy** [comment]
100% of the time when this happens it's because people are running plugins that modify hopper behavior and those plugins override the protection EliteMobs has that prevents this.

**Comment by Clashbestie** [comment]
If he decides to fix this, [EliteMobs has a API Methode to detect if it is a EliteMob Itemstack](https://github.com/MagmaGuy/EliteMobs#elitemobsitemdetector)
