### ISSUE TITLE
Quái elite mob bây giờ quá mạnh

### ISSUE THREAD

**Issue by vudz2310** [MagmaGuy/EliteMobs#109]
đối với quái cấp độ 30 mà tôi mặc giáp cấp độ 70 đánh vẫn gây ra dame quá to
Tôi yêu cầu điều chỉnh lại , dame quái đánh vô người chơi giảm đi , và có thể dùng giáp cấp độ cao hơn để tank hoặc làm quái không gây ra dame với quái lever thấp hơn , chứ thật sự farm rất khó
Nếu được xịn nhà phát triển thêm lệnh ép bảo vệ elite vào giáp bất kì
Cảm ơn vì đã đọc

**Comment by MagmaGuy** [comment]
I don't know where you're getting your level 70 armor from but with that level of reduction you should be getting next to no damage unless you are fighting a boss with an insane damage multiplier.

Do you have other plugins that might be messing with the elitemobs damage?

**Comment by vudz2310** [comment]
> Tôi không biết bạn nhận được áo giáp cấp 70 của mình từ đâu nhưng với mức giảm đó, bạn sẽ không nhận được thiệt hại nào trừ khi bạn đang chiến đấu với một con trùm có hệ số sát thương điên rồ.
> 
> Bạn có các plugin khác có thể gây rắc rối với thiệt hại elitemobs không?

Tôi lấy giáp cấp 70 từ quái ở đấu trường , và giáp ở lệnh ./em simloot 70 100 
tôi đã test 2 loại giáp với nhau và kết quả chúng đều dễ dàng bị quái hạ gục , không biết cách bạn có thể điều chỉnh lại không

**Comment by vudz2310** [comment]
Và điều đó là server tôi farm quái rất kém

**Comment by MagmaGuy** [comment]
You have a huge level difference. This is normal. Level 30 armor and weapons are made to fight level 30 mobs.
