### ISSUE TITLE
Consistent varaible names for configs

### ISSUE THREAD

**Issue by FrozenBeard** [MagmaGuy/EliteMobs#11]
There is a big inconsistency in named variables throughout the files.
the file ItemsCustomLootList.yml has a good consistent layout with properly indented sections.

But files like config.yml have overly insane long variable names, where they should be comments.

For example:
`Use titles to warn players they are missing a permission: true`
Should be something like:

```
# Use titles to warn players they are missing a permission
permTitle: true
```

Using spaces in Variables is nuts. Its just so inconsistent to everything else in the Minecraft spigot world, 99% of plugns follow the same type of structure you have in ItemsCustomLootList, people are used to having configs be neat and clear.

**Comment by MagmaGuy** [comment]
The current configuration system is entirely incompatible with comments. It seemed to be a limitation with the default way minecraft /spigot was handling config defaults back when I first started and I never really bothered to find an alternative. While I appreciate that using descriptive keys is not the usual way of doing things, I have never had an issue with it nor had an issue related to it reported to me.
While doing things more neatly would overall be cool, I am not looking to rewrite the config system at this time, as I've already been putting that off for too long for the sake of other rewrites.

**Comment by FrozenBeard** [comment]
its a mess

**Comment by MagmaGuy** [comment]
I'm accessorizing it with my life.
