### ISSUE TITLE
The task quests is long but there is no page flipping option

### ISSUE THREAD

**Issue by TaylorEevee** [MagmaGuy/EliteMobs#111]
![image](https://user-images.githubusercontent.com/75898916/180679861-628e628a-3e21-46ce-ac96-b1ff31eb15d3.png)
The book is only one page, but it doesn't show everything

**Comment by MagmaGuy** [comment]
I added the option maxCharactersPerBookPage in Quests.yml for the next release of EliteMobs to fix this. Set it to a lower amount.
