### ISSUE TITLE
Failed to read plugin files for custombosses ! && Failed to correctly read entry  in schematic

### ISSUE THREAD

**Issue by TeenBiscuits** [MagmaGuy/EliteMobs#115]
18.08 12:17:22 [Server] WARN [EliteMobs] Failed to correctly read entry  in schematic dungeon dark_cathedral_lair.yml
18.08 12:17:22 [Server] INFO [EliteMobs] [EliteMobs] World em_adventurers_guild found! Loading it in...
18.08 12:17:22 [Server] INFO [EliteMobs] [EliteMobs] World em_adventurers_guild has been successfully loaded! It can be accessed through the '/ag' command, unless you changed that config option!
**18.08 12:17:22 [Server] WARN [EliteMobs] Failed to read plugin files for custombosses ! This is very bad, warn the developer!**
18.08 12:17:22 [Server] WARN java.lang.NullPointerException: Cannot invoke "org.bukkit.plugin.Plugin.isEnabled()" because the return value of "org.bukkit.plugin.PluginManager.getPlugin(String)" is null
18.08 12:17:22 [Server] WARN at EliteMobs-8.0.0-SNAPSHOT-6 .jar//com.magmaguy.elitemobs.config.custombosses.CustomBossesConfigFields.processConfigFields(CustomBossesConfigFields.java:300)
18.08 12:17:22 [Server] WARN at EliteMobs-8.0.0-SNAPSHOT-6 .jar//com.magmaguy.elitemobs.config.CustomConfig.initialize(CustomConfig.java:141)
18.08 12:17:22 [Server] WARN at EliteMobs-8.0.0-SNAPSHOT-6 .jar//com.magmaguy.elitemobs.config.CustomConfig.fileInitializer(CustomConfig.java:90)
18.08 12:17:22 [Server] WARN at EliteMobs-8.0.0-SNAPSHOT-6 .jar//com.magmaguy.elitemobs.config.CustomConfig.directoryCrawler(CustomConfig.java:76)
18.08 12:17:22 [Server] WARN at EliteMobs-8.0.0-SNAPSHOT-6 .jar//com.magmaguy.elitemobs.config.CustomConfig.<init>(CustomConfig.java:59)
18.08 12:17:22 [Server] WARN at EliteMobs-8.0.0-SNAPSHOT-6 .jar//com.magmaguy.elitemobs.config.custombosses.CustomBossesConfig.<init>(CustomBossesConfig.java:16)
18.08 12:17:22 [Server] WARN at EliteMobs-8.0.0-SNAPSHOT-6 .jar//com.magmaguy.elitemobs.EliteMobs.onEnable(EliteMobs.java:250)
18.08 12:17:22 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
18.08 12:17:22 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
18.08 12:17:22 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548)
18.08 12:17:22 [Server] WARN at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:596)
18.08 12:17:22 [Server] WARN at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:510)
18.08 12:17:22 [Server] WARN at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641)
18.08 12:17:22 [Server] WARN at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427)
18.08 12:17:22 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:342)
18.08 12:17:22 [Server] WARN at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1141)
18.08 12:17:22 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310)
18.08 12:17:22 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
18.08 12:17:22 [Server] ERROR Error occurred while enabling EliteMobs v8.0.0-SNAPSHOT-6 (Is it up to date?)

EM Version: 8.0 Snapshot 6

**Comment by MagmaGuy** [comment]
Should be fixed in the latest snapshot.
