### ISSUE TITLE
Boss mob particles spawn with no mob

### ISSUE THREAD

**Issue by FrozenBeard** [MagmaGuy/EliteMobs#12]
Sometimes when a boss mob should spawn it doesnt spawn but the particles appear and wont disappear until next restart

**Comment by MagmaGuy** [comment]
The particle system has been rewritten from scratch over the past two weeks, there is a high probability that this issue has been resolved since then.

**Comment by MagmaGuy** [comment]
Actually let me be more specific here; this bug was fixed in dev build 6.6.2 when I made the switch to despawning action bosses on chunk unload. It's just more thematically fitting.
