### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to EliteMobs v8.5.3 java.lang.IllegalArgumentException: Health must be between 0 and 20.0, but was 33.0. (attribute base value: 20.0, player: )

### ISSUE THREAD

**Issue by BluishBlueMoon** [MagmaGuy/EliteMobs#130]
This issue might not be related to elite mobs!! 
However, I am guessing that the extra health given by elite mobs may not be globally recognized by other plugins !!!!
(( Not sure ))

EliteMobs version: 8.5.3

other plugins might be involved:
- Mythical Races Premium

see the console msg below:

[01:41:40 ERROR]: Could not pass event EntityDamageByEntityEvent to EliteMobs v8.5.3
java.lang.IllegalArgumentException: Health must be between 0 and 20.0, but was 33.0. (attribute base value: 20.0, player: BlueM00N)
        at org.bukkit.craftbukkit.v1_19_R3.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:112) ~[purpur-1.19.4.jar:git-Purpur-1967]
        at com.magmaguy.elitemobs.items.potioneffects.custom.Heal.doHeal(Heal.java:20) ~[EliteMobs (20).jar:?]
        at com.magmaguy.elitemobs.items.potioneffects.PlayerPotionEffects.doOnHitPotionEffect(PlayerPotionEffects.java:117) ~[EliteMobs (20).jar:?]
        at com.magmaguy.elitemobs.items.potioneffects.PlayerPotionEffects.onPlayerHitWithPotionEffect(PlayerPotionEffects.java:106) ~[EliteMobs (20).jar:?]

**Comment by BluishBlueMoon** [comment]
No solution!

**Comment by MagmaGuy** [comment]
> No solution!

To be clear, this is in fact caused by other plugins. Elitemobs has no way to stop other plugins from modifying hp, you need to tell the other authors to stop overriding the health of elite mobs

**Comment by BluishBlueMoon** [comment]
Broooo, that is a lazy reply indicating that you are no longer willing to improve Elitemobs.

Elitemobs is a great plugin, we all love it, and it deserves more improvements to be able to work well with other plugins.

///////
Here is what I have in mind about the issue and solution:
//////


- The error originates in the (Heal.doHeal) method of EliteMobs plugin as per the stack trace shown in the console:
com.magmaguy.elitemobs.items.potioneffects.custom.Heal.doHeal(Heal.java:20)


- The (custom.Heal) method is responsible for applying healing effects, but it is not setting the health value correctly, resulting in the Illegal Argument Exception.

why?

Because: Elitemobs is set to handle health upto 20 and throws an error if health is above, while Other plugins do not mind health being above 20.


Simple Solution:

adjust the configuration related to health-modifying effects within Elitemobs.


How?

Only you know that :)

:)

**Comment by MagmaGuy** [comment]
> Broooo, that is a lazy reply indicating that you are no longer willing to improve Elitemobs.
> 
> Elitemobs is a great plugin, we all love it, and it deserves more improvements to be able to work well with other plugins.
> 
> /////// Here is what I have in mind about the issue and solution: //////
> 
> * The error originates in the (Heal.doHeal) method of EliteMobs plugin as per the stack trace shown in the console:
>   com.magmaguy.elitemobs.items.potioneffects.custom.Heal.doHeal(Heal.java:20)
> * The (custom.Heal) method is responsible for applying healing effects, but it is not setting the health value correctly, resulting in the Illegal Argument Exception.
> 
> why?
> 
> Because: Elitemobs is set to handle health upto 20 and throws an error if health is above, while Other plugins do not mind health being above 20.
> 
> Simple Solution:
> 
> adjust the configuration related to health-modifying effects within Elitemobs.
> 
> How?
> 
> Only you know that :)
> 
> :)

I didn't even read the full error because it looked so similar to a very commonly reported one, and because you were talking about it as though it was still a current bug.

No, [instead this bug was fixed on August 3rd 2023, a year ago](https://github.com/MagmaGuy/EliteMobs/commit/02aedfd8bad502bb040e4ff248a6225d53394174).

**Comment by BluishBlueMoon** [comment]
it seems like I was too lazy as well to snoop around and find the solution :)

thanks, bro
have a good one
