### ISSUE TITLE
MOTD bug

### ISSUE THREAD

**Issue by TritonKing** [MagmaGuy/EliteMobs#135]
Hi,

This may be a low priority issue but I have noticed that after I have enabled the resource pack my server.properties file gets updated and the MOTD section gets added characters after every restart eventually overtaking it. It only happens when color codes and formating is used. Plain MOTD is unaffected.
I thought maybe it was a plugin conflict issue but I can reproduce it on a new server with only Elitemobs, worldguard and worldedit plugins. Everything is fine until I enable the resource pack. Then everytime I restart the server the MOTD gets messed up, more and more with each restart.
Starts off like this: [Imgur](https://imgur.com/TPpVsmk)
Then becomes this: [Imgur](https://imgur.com/FZ7K1l4) then this: [Imgur](https://imgur.com/vCLaD5k) and keeps going: [Imgur](https://imgur.com/J5Pmoz3) every time the server gets restarted. Does anyone else have this issue? Did I miss something?
It only happens after I enable the resource pack and use MOTD formatting. I dont see any errors in the logs.
Thank you 
TK

**Comment by MagmaGuy** [comment]
Now long fixed.
