### ISSUE TITLE
Is there a way to automatically remove all elite mobs from a given world

### ISSUE THREAD

**Issue by aesopcmc** [MagmaGuy/EliteMobs#149]
I have a world that will be reset periodically, and the terrain and all monsters and terrain will be deleted and regenerated. However, the "spawnLocations" configuration in the customboss configuration cannot be automatically cleaned. Is there any relevant instruction to clean it up?

Is there any relevant API or command?

**Comment by MagmaGuy** [comment]
> I have a world that will be reset periodically, and the terrain and all monsters and terrain will be deleted and regenerated. However, the "spawnLocations" configuration in the customboss configuration cannot be automatically cleaned. Is there any relevant instruction to clean it up?
> 
> Is there any relevant API or command?

Is this for shrines or actual dungeons?

**Comment by aesopcmc** [comment]
shrines 

![image](https://github.com/MagmaGuy/EliteMobs/assets/25699609/4b4b7b86-6e62-4bea-9b82-ed51a174fdfb)
