### ISSUE TITLE
Custom Items Not Working

### ISSUE THREAD

**Issue by TheGamingNoodle** [MagmaGuy/EliteMobs#15]
After taking your advice and moving to the Dev build a version for 1.14 to fix a 1.13.2 issue...

> These issues have been resolved months ago in the 1.14 branch, download the dev version if you want a fully functioning version.

Custom Items do not work, the youtube video 'EliteMobs - Making Custom Items' seems to have someone in the comment section having the same issue too but no response has been sent.

That video tells the person watching to use the webtool you made to prevent incorrect formatting; it then mentions to copy/paste the output to ItemCustomLootList.yml (great file names btw); that yml file is non-existant.

I did find a similar one called ItemsUnique.yml; however, the items there have different formats compared to the tool you tell viewers to use.

On the header it contains these fields:
```
Enable unique items: true
Show item worth: true
Enable Mob Hunting set: true
EliteMob percentual spawn chance increase per hunting set item: 10
Enable Zombie King Axe: true
Enable Depths Seeker Fishing Rod: true
Enable Dwarven Greed pickaxe: true
Enable The Feller: true
Enable Space Bow: true
Enable Test Sword 2: true
```
These are not added automatically by the webtool, in addition; the items here are formated with '' apostrophes whereas your webtool formats with quotation marks ("").

See the example:
```
   Test Sword 2:
     Item Type: DIAMOND_SWORD
     Item Name: "Test Sword 2"
     Item Lore:
     - "%aThis Is a test sword to test"
     - "&a The awful design & bugs "
     - "&a This Plugin Has"
     Enchantments:
     - DAMAGE_ALL,20
     Potion Effects:
     - JUMP,2,self,continuous
     Drop Weight: dynamic 
```

Versus:
```
  Hunting Bow:
    Item Type: BOW
    Item Name: '&4Elite Mob Hunting Bow'
    Item Lore:
    - Only for natural-born hunters.
    Enchantments:
    - VANISHING_CURSE,1
    - DAMAGE_ARROW,1
    Potion Effects:
    - SATURATION,1,self,continuous
    Drop Weight: dynamic
    Scalability: dynamic
```
Finally, there is another field that is left blank when using the webtool; that is the 'scalability' field which is set to dynamic or continuous. There is no information on the wiki regarding that field and what it does.

After making sure the syntax and all fields were corrected to include all information other items seem to have; I am still unable to bring the item up in-game.
I have run the commands /em getloot and it is not there; also tried getting the loot by name; /em getloot Test Sword 2.

After investigating more; the command /em getloot [item_name] does not work even with items that do exist;

This plugin seems really cool but if it is not going to work please just say so I can move on with my life and look into other plugins.

**Comment by MagmaGuy** [comment]
Man I feel bad that you wrote an entire thesis over this when your issue is rather simple. The dev version has a new custom item system that has been simplified from previous versions. All custom items are now stored in the custom items directory and follow a new format. The reason why the dev version hasn't been released yet is because I am working on the new webapp for it, as well as various documentation. I recommend you join the discord server associated to the plugin for swifter response times.
