### ISSUE TITLE
No working EliteMobs and FreeMinecraftModels in 1.20.6

### ISSUE THREAD

**Issue by XxfMarkfxX** [MagmaGuy/EliteMobs#151]
![Screenshot_39](https://github.com/MagmaGuy/EliteMobs/assets/170231604/dbb50a85-53f1-4047-8136-9e425a260518)

**Comment by MagmaGuy** [comment]
1.19.4-1.20.4 are supported with EliteMobs 8
1.21+ is supported with EliteMobs 9
1.20.5 and 1.20.6 are not supported.
