### ISSUE TITLE
Please add support for Folia server

### ISSUE THREAD

**Issue by Q2297045667** [MagmaGuy/EliteMobs#154]
More and more people are starting to use Folia, and the current version is also relatively stable
https://github.com/PaperMC/Folia

**Comment by MagmaGuy** [comment]
It is my understanding that it would require some pretty massive changes so I am not interested at this time

**Comment by Euphillya** [comment]
@Q2297045667 I started the support, you just need to compile it : https://github.com/Euphillya/EliteMobs-Folia
