### ISSUE TITLE
New Player Error

### ISSUE THREAD

**Issue by Rossal1** [MagmaGuy/EliteMobs#156]
16.06 09:38:15 [Server] INFO [NewPlayer] joined the game
16.06 09:38:16 [Server] WARN Something went wrong while generating a new player entry. This is bad! Tell the dev.
16.06 09:38:16 [Server] WARN com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 6,049,295 milliseconds ago. The last packet sent successfully to the server was 6,049,295 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
16.06 09:38:18 [Server] WARN Failed to get integer value from database!
16.06 09:38:18 [Server] WARN java.sql.SQLException: Illegal operation on empty result set.
16.06 09:38:18 [Server] WARN at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
16.06 09:38:18 [Server] WARN at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:98)
16.06 09:38:18 [Server] WARN at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:90)
16.06 09:38:18 [Server] WARN at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:64)
16.06 09:38:18 [Server] WARN at com.mysql.cj.jdbc.result.ResultSetImpl.checkRowPos(ResultSetImpl.java:528)
16.06 09:38:18 [Server] WARN at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1259)
16.06 09:38:18 [Server] WARN at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:826)
16.06 09:38:18 [Server] WARN at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:847)
16.06 09:38:18 [Server] WARN at EliteMobs.jar//com.magmaguy.elitemobs.playerdata.database.PlayerData.getDatabaseInteger(PlayerData.java:533)
16.06 09:38:18 [Server] WARN at EliteMobs.jar//com.magmaguy.elitemobs.playerdata.database.PlayerData.getActiveGuildLevel(PlayerData.java:238)
16.06 09:38:18 [Server] WARN at EliteMobs.jar//com.magmaguy.elitemobs.adventurersguild.GuildRank.getActiveGuildRank(GuildRank.java:61)
16.06 09:38:18 [Server] WARN at EliteMobs.jar//com.magmaguy.elitemobs.adventurersguild.GuildRank$GuildRankEvents$1.run(GuildRank.java:241)
16.06 09:38:18 [Server] WARN at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)
16.06 09:38:18 [Server] WARN at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
16.06 09:38:18 [Server] WARN at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1734)
16.06 09:38:18 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:503)
16.06 09:38:18 [Server] WARN at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1606)
16.06 09:38:18 [Server] WARN at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1260)
16.06 09:38:18 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
16.06 09:38:18 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:1583)
16.06 09:38:18 [Server] WARN Task #524249 for EliteMobs v8.7.15 generated an exception
16.06 09:38:18 [Server] INFO java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "com.magmaguy.elitemobs.playerdata.database.PlayerData.getDatabaseInteger(java.util.UUID, String)" is null
16.06 09:38:18 [Server] INFO at EliteMobs.jar/com.magmaguy.elitemobs.playerdata.database.PlayerData.getActiveGuildLevel(PlayerData.java:238) ~[EliteMobs.jar:?]
16.06 09:38:18 [Server] INFO at EliteMobs.jar/com.magmaguy.elitemobs.adventurersguild.GuildRank.getActiveGuildRank(GuildRank.java:61) ~[EliteMobs.jar:?]
16.06 09:38:18 [Server] INFO at EliteMobs.jar/com.magmaguy.elitemobs.adventurersguild.GuildRank$GuildRankEvents$1.run(GuildRank.java:241) ~[EliteMobs.jar:?]
16.06 09:38:18 [Server] INFO at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
16.06 09:38:18 [Server] INFO at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
16.06 09:38:18 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1734) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
16.06 09:38:18 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:503) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
16.06 09:38:18 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1606) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
16.06 09:38:18 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1260) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
16.06 09:38:18 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
16.06 09:38:18 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

16.06 09:39:35 [Server] WARN Failed to get blob value from database!
16.06 09:39:35 [Server] WARN UUID: 696fe8e0-8c0a-4525-b483-874637889011 | Value: QuestStatus
16.06 09:39:35 [Server] WARN java.sql.SQLException: Illegal operation on empty result set.
16.06 09:39:35 [Server] WARN at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
16.06 09:39:35 [Server] WARN at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:98)
16.06 09:39:35 [Server] WARN at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:90)
16.06 09:39:35 [Server] WARN at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:64)
16.06 09:39:35 [Server] WARN at com.mysql.cj.jdbc.result.ResultSetImpl.checkRowPos(ResultSetImpl.java:528)
16.06 09:39:35 [Server] WARN at com.mysql.cj.jdbc.result.ResultSetImpl.getBytes(ResultSetImpl.java:725)
16.06 09:39:35 [Server] WARN at com.mysql.cj.jdbc.result.ResultSetImpl.getBytes(ResultSetImpl.java:732)
16.06 09:39:35 [Server] WARN at EliteMobs.jar//com.magmaguy.elitemobs.playerdata.database.PlayerData.getDatabaseBlob(PlayerData.java:361)
16.06 09:39:35 [Server] WARN at EliteMobs.jar//com.magmaguy.elitemobs.playerdata.database.PlayerData.getQuests(PlayerData.java:253)
16.06 09:39:35 [Server] WARN at EliteMobs.jar//com.magmaguy.elitemobs.quests.objectives.CustomFetchObjective.checkEvent(CustomFetchObjective.java:49)
16.06 09:39:35 [Server] WARN at EliteMobs.jar//com.magmaguy.elitemobs.quests.objectives.CustomFetchObjective$CustomFetchObjectiveEvents.onItemPickup(CustomFetchObjective.java:124)
16.06 09:39:35 [Server] WARN at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor817.execute(Unknown Source)
16.06 09:39:35 [Server] WARN at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
16.06 09:39:35 [Server] WARN at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
16.06 09:39:35 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
16.06 09:39:35 [Server] WARN at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
16.06 09:39:35 [Server] WARN at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
16.06 09:39:35 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627)
16.06 09:39:35 [Server] WARN at net.minecraft.world.entity.item.ItemEntity.playerTouch(ItemEntity.java:529)
16.06 09:39:35 [Server] WARN at net.minecraft.world.entity.player.Player.touch(Player.java:673)
16.06 09:39:35 [Server] WARN at net.minecraft.world.entity.player.Player.aiStep(Player.java:638)
16.06 09:39:35 [Server] WARN at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3189)
16.06 09:39:35 [Server] WARN at net.minecraft.world.entity.player.Player.tick(Player.java:315)
16.06 09:39:35 [Server] WARN at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:864)
16.06 09:39:35 [Server] WARN at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:360)
16.06 09:39:35 [Server] WARN at net.minecraft.network.Connection.tick(Connection.java:639)
16.06 09:39:35 [Server] WARN at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:242)
16.06 09:39:35 [Server] WARN at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1837)
16.06 09:39:35 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:503)
16.06 09:39:35 [Server] WARN at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1606)
16.06 09:39:35 [Server] WARN at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1260)
16.06 09:39:35 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
16.06 09:39:35 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:1583)
16.06 09:39:41 [Server] WARN Failed to get blob value from database!
16.06 09:39:41 [Server] WARN UUID: 696fe8e0-8c0a-4525-b483-874637889011 | Value: QuestStatus
16.06 09:39:41 [Server] WARN java.sql.SQLException: Illegal operation on empty result set.
16.06 09:39:41 [Server] WARN at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
16.06 09:39:41 [Server] WARN at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:98)
16.06 09:39:41 [Server] WARN at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:90)
16.06 09:39:41 [Server] WARN at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:64)
16.06 09:39:41 [Server] WARN at com.mysql.cj.jdbc.result.ResultSetImpl.checkRowPos(ResultSetImpl.java:528)
16.06 09:39:41 [Server] WARN at com.mysql.cj.jdbc.result.ResultSetImpl.getBytes(ResultSetImpl.java:725)
16.06 09:39:41 [Server] WARN at com.mysql.cj.jdbc.result.ResultSetImpl.getBytes(ResultSetImpl.java:732)
16.06 09:39:41 [Server] WARN at EliteMobs.jar//com.magmaguy.elitemobs.playerdata.database.PlayerData.getDatabaseBlob(PlayerData.java:361)
16.06 09:39:41 [Server] WARN at EliteMobs.jar//com.magmaguy.elitemobs.playerdata.database.PlayerData.getQuests(PlayerData.java:253)
16.06 09:39:41 [Server] WARN at EliteMobs.jar//com.magmaguy.elitemobs.quests.objectives.CustomFetchObjective.checkEvent(CustomFetchObjective.java:49)
16.06 09:39:41 [Server] WARN at EliteMobs.jar//com.magmaguy.elitemobs.quests.objectives.CustomFetchObjective$CustomFetchObjectiveEvents.onItemPickup(CustomFetchObjective.java:124)
16.06 09:39:41 [Server] WARN at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor817.execute(Unknown Source)
16.06 09:39:41 [Server] WARN at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
16.06 09:39:41 [Server] WARN at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
16.06 09:39:41 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
16.06 09:39:41 [Server] WARN at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
16.06 09:39:41 [Server] WARN at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
16.06 09:39:41 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627)
16.06 09:39:41 [Server] WARN at net.minecraft.world.entity.item.ItemEntity.playerTouch(ItemEntity.java:529)
16.06 09:39:41 [Server] WARN at net.minecraft.world.entity.player.Player.touch(Player.java:673)
16.06 09:39:41 [Server] WARN at net.minecraft.world.entity.player.Player.aiStep(Player.java:638)
16.06 09:39:41 [Server] WARN at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3189)
16.06 09:39:41 [Server] WARN at net.minecraft.world.entity.player.Player.tick(Player.java:315)
16.06 09:39:41 [Server] WARN at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:864)
16.06 09:39:41 [Server] WARN at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:360)
16.06 09:39:41 [Server] WARN at net.minecraft.network.Connection.tick(Connection.java:639)
16.06 09:39:41 [Server] WARN at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:242)
16.06 09:39:41 [Server] WARN at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1837)
16.06 09:39:41 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:503)
16.06 09:39:41 [Server] WARN at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1606)
16.06 09:39:41 [Server] WARN at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1260)
16.06 09:39:41 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
16.06 09:39:41 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:1583)
16.06 09:39:58 [Server] WARN Failed to get blob value from database!
16.06 09:39:58 [Server] WARN UUID: 696fe8e0-8c0a-4525-b483-874637889011 | Value: QuestStatus
16.06 09:39:58 [Server] WARN java.sql.SQLException: Illegal operation on empty result set.
16.06 09:39:58 [Server] WARN at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
16.06 09:39:58 [Server] WARN at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:98)
16.06 09:39:58 [Server] WARN at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:90)
16.06 09:39:58 [Server] WARN at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:64)
16.06 09:39:58 [Server] WARN at com.mysql.cj.jdbc.result.ResultSetImpl.checkRowPos(ResultSetImpl.java:528)
16.06 09:39:58 [Server] WARN at com.mysql.cj.jdbc.result.ResultSetImpl.getBytes(ResultSetImpl.java:725)
16.06 09:39:58 [Server] WARN at com.mysql.cj.jdbc.result.ResultSetImpl.getBytes(ResultSetImpl.java:732)
16.06 09:39:58 [Server] WARN at EliteMobs.jar//com.magmaguy.elitemobs.playerdata.database.PlayerData.getDatabaseBlob(PlayerData.java:361)
16.06 09:39:58 [Server] WARN at EliteMobs.jar//com.magmaguy.elitemobs.playerdata.database.PlayerData.getQuests(PlayerData.java:253)
16.06 09:39:58 [Server] WARN at EliteMobs.jar//com.magmaguy.elitemobs.quests.objectives.CustomFetchObjective.checkEvent(CustomFetchObjective.java:49)
16.06 09:39:58 [Server] WARN at EliteMobs.jar//com.magmaguy.elitemobs.quests.objectives.CustomFetchObjective$CustomFetchObjectiveEvents.onItemPickup(CustomFetchObjective.java:124)
16.06 09:39:58 [Server] WARN at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor817.execute(Unknown Source)
16.06 09:39:58 [Server] WARN at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
16.06 09:39:58 [Server] WARN at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
16.06 09:39:58 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
16.06 09:39:58 [Server] WARN at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
16.06 09:39:58 [Server] WARN at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
16.06 09:39:58 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627)
16.06 09:39:58 [Server] WARN at net.minecraft.world.entity.item.ItemEntity.playerTouch(ItemEntity.java:529)
16.06 09:39:58 [Server] WARN at net.minecraft.world.entity.player.Player.touch(Player.java:673)
16.06 09:39:58 [Server] WARN at net.minecraft.world.entity.player.Player.aiStep(Player.java:638)
16.06 09:39:58 [Server] WARN at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3189)
16.06 09:39:58 [Server] WARN at net.minecraft.world.entity.player.Player.tick(Player.java:315)
16.06 09:39:58 [Server] WARN at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:864)
16.06 09:39:58 [Server] WARN at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:360)
16.06 09:39:58 [Server] WARN at net.minecraft.network.Connection.tick(Connection.java:639)
16.06 09:39:58 [Server] WARN at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:242)
16.06 09:39:58 [Server] WARN at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1837)
16.06 09:39:58 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:503)
16.06 09:39:58 [Server] WARN at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1606)
16.06 09:39:58 [Server] WARN at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1260)
16.06 09:39:58 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
16.06 09:39:58 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by MagmaGuy** [comment]
If you are still having this issue get support on the discord server, but I think it's already been resolved
