### ISSUE TITLE
Potion effects won't go away after boss despawns

### ISSUE THREAD

**Issue by broohellnah** [MagmaGuy/EliteMobs#160]
so, i am stuck with some weird effects, i have slowness. the boss i was fighting gave slowness but it despawned and now i'm stuck with that. i'm on latest paper server. also, if i open my inventory, it does not show any effect, and /effect clear gamerGamer1 says i got no effects. Also good to note; at the server start elitemobs says something about potion effects. https://pastebin.com/cRgrLL8C 

How to reproduce:

get a boss that gives a effect, also have the plugin back  (/back) enabled. try to defeat the boss, but just die and do /back over and over until the boss despawns.

issue is solved, you gotta drink a potion of the same effects you're stuck with. will post this still.

**Comment by broohellnah** [comment]
im new to github can't flipping doa anything sorry

**Comment by MagmaGuy** [comment]
> so, i am stuck with some weird effects, i have slowness. the boss i was fighting gave slowness but it despawned and now i'm stuck with that. i'm on latest paper server. also, if i open my inventory, it does not show any effect, and /effect clear gamerGamer1 says i got no effects. Also good to note; at the server start elitemobs says something about potion effects. https://pastebin.com/cRgrLL8C
> 
> How to reproduce:
> 
> get a boss that gives a effect, also have the plugin back (/back) enabled. try to defeat the boss, but just die and do /back over and over until the boss despawns.
> 
> issue is solved, you gotta drink a potion of the same effects you're stuck with. will post this still.

This should definitely be fixed.
