### ISSUE TITLE
EasyMinecraftGoals not available

### ISSUE THREAD

**Issue by PikaMug** [MagmaGuy/EliteMobs#167]
Depending on EliteMobs 9.0.2-SNAPSHOT (per README) in a Maven project results in the following error:

`Could not find artifact com.magmaguy:EasyMinecraftGoals-dist:pom:1.11.2-SNAPSHOT in spigot-repo (https://hub.spigotmc.org/nexus/content/repositories/snapshots/)`

Also tried with 9.0.4-SNAPSHOT (newest version in repo) and forced update, same issue.

Repositories:

```xml
<repositories>
    <repository>
        <id>spigot-repo</id>
        <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
    </repository>
    <repository>
        <id>codemc-repo</id>
        <url>https://repo.codemc.io/repository/maven-public/</url>
    </repository>
    <repository>
        <id>elitemobs-repo</id>
        <url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

**Comment by MagmaGuy** [comment]
My bad, I moved all my repos but it was in the middle of doing so many things I have no yet documented it fully.

The new repo for all of my plugins is located at 

https://repo.magmaguy.com/

In this instance, you're looking for 

```
<repository>
  <id>magmaguy-repo-releases</id>
  <name>MagmaGuy's Repository</name>
  <url>https://repo.magmaguy.com/releases</url>
</repository>

<dependency>
  <groupId>com.magmaguy</groupId>
  <artifactId>EasyMinecraftGoals-dist</artifactId>
  <version>1.13.0</version>
</dependency>
```

**Comment by PikaMug** [comment]
@MagmaGuy Not a problem. Unfortunately, even the new builds have an issue:

`The following artifacts could not be resolved: com.magmaguy:EasyMinecraftGoals-manager:pom:1.13.0 (absent): com.magmaguy:EasyMinecraftGoals-manager:pom:1.13.0 was not found in https://hub.spigotmc.org/nexus/content/repositories/snapshots/ during a previous attempt.
`

It looks like EasyMinecraftGoals-manager is missing from the repo.

**Comment by MagmaGuy** [comment]
> @MagmaGuy Not a problem. Unfortunately, even the new builds have an issue:
> 
> `The following artifacts could not be resolved: com.magmaguy:EasyMinecraftGoals-manager:pom:1.13.0 (absent): com.magmaguy:EasyMinecraftGoals-manager:pom:1.13.0 was not found in https://hub.spigotmc.org/nexus/content/repositories/snapshots/ during a previous attempt. `
> 
> It looks like EasyMinecraftGoals-manager is missing from the repo.

Seems like you're looking for EasyMinecraftGoals-manager not EasyMinecraftGoals-dist which I believe should be working from what I'm seeing on my end but let me know if that is not the case. It's the dependency I posted above.

**Comment by PikaMug** [comment]
@MagmaGuy I'm just trying to depend on EliteMobs as follows:

```xml
<repository>
    <id>magmaguy-repo-releases</id>
    <name>MagmaGuy's Repository</name>
    <url>https://repo.magmaguy.com/releases</url>
</repository>
<dependency>
    <groupId>org.spigotmc</groupId>
    <artifactId>spigot-api</artifactId>
    <version>1.13.2-R0.1-SNAPSHOT</version>
    <scope>provided</scope>
</dependency>
```

EliteMobs depends on `EasyMinecraftGoals-dist` (or something else which uses it) which itself apparently depends on `EasyMinecraftGoals-manager`. As of writing, only -dist is available in your repository:

![repo](https://github.com/user-attachments/assets/6146a618-dc0a-475d-a33e-9f57272e767f)

My guess is you're able to compile because you have -manager cached locally. For everyone else, I think you'd need to either put -manager in the repo, or the whole `EasyMinecraftGoals` project and update EliteMobs and other plugins to depend on that instead.

**Comment by MagmaGuy** [comment]
> aguy:EasyMinecraftGoals-manager:pom:1.13.0 was not found in https://hub.spigotmc.org/nexus/content/reposi

My bad, figured it out just now, it should work. Thanks for your reporting and patience!
