### ISSUE TITLE
MagmaCore not available

### ISSUE THREAD

**Issue by PikaMug** [MagmaGuy/EliteMobs#174]
In a similar vein to #167 when depending on the latest repo EliteMobs, it (or one of its dependencies) requires MagmaCore 1.0-SNAPSHOT, but only versions 1.8, 1.9, and 1.10 are [available in the repo](https://repo.magmaguy.com/#/releases/com/magmaguy/MagmaCore).

```xml
<repository>
    <id>magmaguy-repo-releases</id>
    <name>MagmaGuy's Repository</name>
    <url>https://repo.magmaguy.com/releases</url>
</repository>
<dependency>
    <groupId>com.magmaguy</groupId>
    <artifactId>EliteMobs</artifactId>
    <version>9.1.6</version>
</dependency>
```

`Cannot resolve com.magmaguy:MagmaCore:1.0-SNAPSHOT`

**Comment by MagmaGuy** [comment]
> In a similar vein to #167 when depending on the latest repo EliteMobs, it (or one of its dependencies) requires MagmaCore 1.0-SNAPSHOT, but only versions 1.8, 1.9, and 1.10 are [available in the repo](https://repo.magmaguy.com/#/releases/com/magmaguy/MagmaCore).
> 
> ```
> <repository>
>     <id>magmaguy-repo-releases</id>
>     <name>MagmaGuy's Repository</name>
>     <url>https://repo.magmaguy.com/releases</url>
> </repository>
> <dependency>
>     <groupId>com.magmaguy</groupId>
>     <artifactId>EliteMobs</artifactId>
>     <version>9.1.6</version>
> </dependency>
> ```
> 
> `Cannot resolve com.magmaguy:MagmaCore:1.0-SNAPSHOT`

Yep that's definitely my bad, I cleaned up the repo when I released EasyMinecraftGoals and didn't realize I was still using that. It is now up.

**Comment by PikaMug** [comment]
@MagmaGuy Thanks, is there an amount of time to wait before it updates? I'm not seeing any change to the repo (no new MagmaCore or EliteMobs versions).

**Comment by MagmaGuy** [comment]
> @MagmaGuy Thanks, is there an amount of time to wait before it updates? I'm not seeing any change to the repo (no new MagmaCore or EliteMobs versions).

It's a snapshot release so it's in the snapshots

**Comment by PikaMug** [comment]
> > @MagmaGuy Thanks, is there an amount of time to wait before it updates? I'm not seeing any change to the repo (no new MagmaCore or EliteMobs versions).
> 
> It's a snapshot release so it's in the snapshots
> 
> https://repo.magmaguy.com/#/snapshots/com/magmaguy/MagmaCore

I see, looking forward to release then. Thank you!
