### ISSUE TITLE
low tps on disabled world

### ISSUE THREAD

**Issue by makegodhere** [MagmaGuy/EliteMobs#183]
when player flying in world - tps lower than 11
![image](https://github.com/user-attachments/assets/6af1b55e-b316-4844-a00a-1a5f44b2496f)
![image](https://github.com/user-attachments/assets/3dee6a62-6a09-4855-a0e7-da5d635e853c)
![image](https://github.com/user-attachments/assets/d9cbde75-fbf3-44db-bc69-1080994213b5)

world disabled in validworld confing

**Comment by MagmaGuy** [comment]
I would need the actual timings report to see what is going on here

**Comment by makegodhere** [comment]
> I would need the actual timings report to see what is going on here

Im sorry. I found a problem in another plugin. Thank you for fast answer. Love you work and plugins!
