### ISSUE TITLE
[API] Add custom loot drop to EliteMobDeathEvent

### ISSUE THREAD

**Issue by Paul2708** [MagmaGuy/EliteMobs#19]
Hey!

I was about to modify and customize the loot drop, that spawns if an elite mob dies.
Unfortunately the spawned loot drop is not included in `EliteMobDeathEvent` or `EntityDeathEvent#getDrops()`.

Is there a way to get the loot drops?
If not, would you accept a pull request that includes the loot to `EliteMobDeathEvent`?

Greetings, Paul

**Comment by MagmaGuy** [comment]
I'm adding customization of drops as a config settings very soon. I'll add the elite loot to the death event. However, I do not accept any pull requests. This is simply because I want 100% of the code in EliteMobs to be mine. I am more than happy to hear any suggestions you might have, though.
