### ISSUE TITLE
All chest-gui interfaces don't work as intended.

### ISSUE THREAD

**Issue by reecepounder** [MagmaGuy/EliteMobs#20]
Hello.
We run EliteMobs on our server, and any time we run /ag or /elitemobs shop, the window opens but the shop itself is just like a chest; players can remove items (namely diamond swords and emeralds) one at a time. This has been abused and we've had to turn it off for now.

Why is this happening and can we fix it?
Note: I have no access to the console for 7 days

**Comment by reecepounder** [comment]
![image](https://user-images.githubusercontent.com/53270052/65838390-8c834980-e2d0-11e9-8454-07c004819f6f.png)
These are all the Difficulty sword from /ag

**Comment by MagmaGuy** [comment]
100% chance you are not using the right version. Use the latest dev version, not the public build.
