### ISSUE TITLE
MineTinker Compatability

### ISSUE THREAD

**Issue by DerMongoose** [MagmaGuy/EliteMobs#22]
Could we potentially get some enchantment compatability with MineTinker so that MineTinker weapons do not become tedious and so armor do not become obsolete when facing Elites, as Elite Protection cannot be applied to MineTinker items, meaning damage from Elites ramps up heavily when wearing something that isn't an EliteMobs armor piece, especially against bosses.

I do have an interesting solution to make it so that MineTinker items do not become obsolete, yet EliteMobs items have their own unique advantage, allowing players to choose between one type of item or another:
Elites can rarely drop a custom Modifier that will apply an EliteMobs enchantment to a MineTinker item; players will also be able to craft these modifiers, however, the modifiers crafted by players will only be able to be applied to a MineTinker item if it has a modifier slot available, whereas modifiers dropped by Elites can be applied regardless and will not take up a modifier slot.

Some examples of EliteMobs enchantments as MineTinker modifiers are:

Elite's Bane Modifier (Haunted Gold): A catch-all modifier for Elite Sharpness, Elite Power, and Elite Protection that uses a Gold Ingot as a base model.  The modifier is crafted either through enchantment of a Gold Ingot (right-clicking the desired item on a bookshelf, which will consume 10 levels of experience in the process), or through crafting together an ender eye, four gold ingots, a rottem flesh, a bone, a spider eye, and a gunpowder.  The modifier likely won't have a cap or at least a very high one to reflect the EliteMobs enchantment, and is the most likely modifier to drop off an Elite.

Hunting Modifier (Hunting Eye):  This modifier uses an Ender Eye as a base model and applies the Hunter enchant.  The modifier can be crafted by surrounding a compas with 4 ender eyes and 4 ender pearls or phantom membranes (your choice).  This modifier will have a capacity of 3, just like the enchantment, and is a more uncommon modifier to drop.

Critical Modifier (Heavy Flint):  This modifier uses a flint as a base model and applies the Critical Strikes enchantment.  The modifier can be crafted by placing 4 obsidian and 4 iron around a flint, and will likely have a capacity of 10 or possibly less, and is as likely to drop as the Hunting modifier.

I hope this gets read and acknowledged, so that we could potentially get more addons to mesh and be compatable with EliteMobs, as it is a really good addon.

**Comment by MagmaGuy** [comment]
I don't do that level of compatibility with third party plugins and the fact I've never even heard of MineTinker is a big part of why.  It is simply not feasible to do extensive third party support - if I did, I wouldn't be able to accept due to the backlog of dozens upon dozens of plugins which would each require in-depth changes to how EliteMobs works.

You are free to create your own branch of the plugin or addon to do it yourself.
