### ISSUE TITLE
Terrible lag when using /elitemobs shop

### ISSUE THREAD

**Issue by Matrixchung** [MagmaGuy/EliteMobs#25]
Hi there, I had a terrible problem these days when I try to use /elitemobs shop in my Paper 1.15.2 server.It seems that this command will cause the main server thread to stop respond for more than a minute.I use CitizensCMD to bind the command on a NPC in my server,and when I try to execute it manually,I will meet the same problem.

EliteMobs version: EliteMobs 7.1.0 and 7.1.1 both tested
Server Core: Paper version git-Paper-66 (MC: 1.15.2)
Env:Windows Server 2019 with JRE 8u241

![20200225204557](https://user-images.githubusercontent.com/20507354/75249129-902fe380-5810-11ea-8c41-6793f3123810.jpg)

**Comment by MagmaGuy** [comment]
Please try the latest dev build, I believe it's been fixed.

**Comment by Matrixchung** [comment]
> Please try the latest dev build, I believe it's been fixed.

I will update it to the newest later and try.Thanks for your reply!
