### ISSUE TITLE
Ability to (re)set a user tier

### ISSUE THREAD

**Issue by FesterHead** [MagmaGuy/EliteMobs#29]
User story:  As a server operator, I want the ability to set a players tier level so that I can manually, or programmatically via commands, increase or decrease a players EliteMobs tier.

Specific use case:  I have  Skyblock server that when an /island reset command is entered by a player it not only resets their island it also resets their vault balance, EliteMobs balance, mcMMO scores, Jobs Reborn scores, flight time, end experience.  The only thing I cannot do is drop a player EliteMobs tier down to the start.  Essentially, my players want to completely start over when resetting their island.

To reset an EliteMobs balance, the command is `elitemobs set [player] 0`

I'd like something similar such as `elitemobs settier [player] 1` where 1 represent the AdenturersGuild.yml value for **Fresh Meat**

**Comment by MagmaGuy** [comment]
Will be added very shortly.
