### ISSUE TITLE
Natural Mobs Spawn

### ISSUE THREAD

**Issue by Fargus5** [MagmaGuy/EliteMobs#3]
Hi, I have disabled it, but  elite mobs spawn at the same in each world

**Comment by MagmaGuy** [comment]
I recommend you use the discord channel for this kind of support. Are you sure that the Mobs still spawn at high levels and aren't just stacking?

**Comment by Fargus5** [comment]
I don't know but they spawn . I don't know if they are stacking

**Comment by MagmaGuy** [comment]
Ok, I'm not sure what you're trying to do. Can you try to be a bit more detailed about what you're trying to accomplish and what you've done to try to accomplish it?

**Comment by Fargus5** [comment]
I close this issue, becouse was my misunderstanding with stacking mobs
