### ISSUE TITLE
Something went wrong while using /em shop

### ISSUE THREAD

**Issue by Dimerbone** [MagmaGuy/EliteMobs#30]
Hi there, I had a problem when I try to use "/elitemobs shop" in my Paper 1.15.2 server.It should have openned the menu "EliteMobs/menus/procedural_shop_menu.yml" ,however it actually openned "Elitemobs/menus/custom_shop_menus.yml" — the same as "/em cshop" . I tried to reset the configurations , but the problem still remained there.

[ScreenRecord.zip](https://github.com/MagmaGuy/EliteMobs/files/4572799/ScreenRecord.zip)

EliteMobs version: EliteMobs 7.1.0
Server_Core: Paper_1.15.2_b227 (MC: 1.15.2)
Env:WinServer 2016 with JRE 8u131

**Comment by MagmaGuy** [comment]
It's hard to tell from the recording, are you sure it's not an issue with the translation?
It could be that the translation uses the same name for both shops by mistake. 
Try opening the shop and see if the contents are different between the two. If that's the case, you just need to fix the name of the shop in the configuration files.

**Comment by Dimerbone** [comment]
I'm sure it's not caused by translation , cuz I've tried running it without translation but default configs .
Could you tell me which file and which part of letters I should change to fix the name of the shop ?
THX !
