### ISSUE TITLE
Nothing Happen When Clicking Shop Items (Player cannot buy or sell)

### ISSUE THREAD

**Issue by wangyz1999** [MagmaGuy/EliteMobs#32]
In the shop GUI opened after right-clicking the blacksmith and special-blacksmith, the items are listed, but nothing happens when trying to buy them, there is no notification about anything.
Players cannot sell items either.

**Comment by JackySky** [comment]
I can confirm this is happening in Paper 1.15.2 with EliteMob 7.1.0.
Shop does not work, can't buy, and selling anything return error.
Switching the server back to Spigot worked for me. Still, the items dropped in Paper cannot be sold too.

**Comment by JackySky** [comment]
I think I figured it out. Version 7.1.0 listed in Spigot page is using the deprecated `getCustomTagContainer()` in ItemTagger and paper isn't liking it. Just checkout experimental branch and build 7.1.22 instead. No code change required. Seems to be working smoothly now.

**Comment by MagmaGuy** [comment]
Fixed.
