### ISSUE TITLE
Incompatibility with BetterDrops

### ISSUE THREAD

**Issue by Aibakins** [MagmaGuy/EliteMobs#40]
![image](https://user-images.githubusercontent.com/1620028/100687328-15bb6380-334e-11eb-8763-9a604d596dab.png)

Plugin in question: https://www.spigotmc.org/resources/betterdrops.7497/

Is there a way to disable naming entities created by the elitemob effects?

**Comment by MagmaGuy** [comment]
Fixed for the next release using the BetterDrops metadata system.
