### ISSUE TITLE
How to give item to another player?

### ISSUE THREAD

**Issue by Cyliann** [MagmaGuy/EliteMobs#41]
Any idea how can I give another player an item I dropped from elite mob? (when I drop it on the flor, they can't pick it up)
/shareitem does not work. 
Eventually I can totally turn off soulbounds to items, but I don't know how to do that either.

**Comment by MagmaGuy** [comment]
/shareitem is for sharing it on chat.

/em unbind is for removing soulbind from an item. There will be an update very soon adding mechanics for removing soulbind from items.

**Comment by Cyliann** [comment]
Thanks a lot_
