### ISSUE TITLE
[EliteMobs] Failed to assign custom disguise custom:skin1! Did you configure the disguise correctly?

### ISSUE THREAD

**Issue by NomansnowYT** [MagmaGuy/EliteMobs#42]
Here's The Log
https://mclo.gs/7o5L0Vr

Config Of The Custom Boss
isEnabled: true
entityType: SKELETON
name: '&6Exusiai'
level: dynamic
timeout: 60
healthMultiplier: 20.0
damageMultiplier: 16.5
mainHand: 'BOW'
isBaby: false
powers:
- attack_arrow.yml
- attack_freeze.yml
- skeleton_tracking_arrow.yml
spawnMessage: '&6A Wild Exusiai Has Been Spotted!'
deathMessages:
- '&e&l---------------------------------------------'
- '&6Exusiai has been slain!'
- '&c&l    1st Damager: $damager1name &cwith $damager1damage damage!'
- '&6&l    2nd Damager: $damager2name &6with $damager2damage damage!'
- '&e&l    3rd Damager: $damager3name &ewith $damager3damage damage!'
- '&aSlayers: $players'
- '&e&l---------------------------------------------'
escapeMessage: '&6Exusiai Has Escaped!'
locationMessage: '&6Exusiai Is $distance Block Away!'
uniqueLootList:
- UWU.yml:1
- Exusiai_Apple_Pie.yml:1
dropsEliteMobsLoot: true
dropsVanillaLoot: false
trails:
- "HEART"
onDamageMessages:
- '&6하아! 나는 당신을 죽일 것입니다! (Ha! I Will Kill You!)'
- '&6움직이지 마! (Stop Moving!)'
- '&6You Simp! Now I Will Punish You!'
- '&6내 사과 파이를 훔쳤습니까? (Did You Steal My Apple Pie?)'
onDamagedMessages:
- '&6야 그만 치지! (Ow Stop Hitting Me!)'
- '&6텍사스 도움말! (Texas Help!)'
- '&6내가 너를 돌봐 줄게 (Let Me Take Care Of You)'
- '&6(︶︹︺)'
announcementPriority: 2
followDistance: 57
disguise: custom:skin1
frozen: false
isPersistent: true
spawnChance: 1.5

**Comment by MagmaGuy** [comment]
Sounds like you didn't configure the disguise correctly. This is a libsdisguises issue, not an elitemobs one.
