### ISSUE TITLE
Quest issue

### ISSUE THREAD

**Issue by BloOdlyne** [MagmaGuy/EliteMobs#44]
Hi,

I've noticed an issue with the quest "Slain 12 Lvl 20+ Elite Husk". Accepting the question everything seems ok, but when you try to actually achieve the quest it doesn't count it.
I've tried manually spawning a mob down with lvl21 and the same results.

Did pick up another quest from the quest giver "Slain 8 Elite Blaze". I've spawned the Elite blaze into the overworld and it was counted as it should be.

My guess would be that the issue is only affecting the Elite Husks (although I haven't tested the rest of the quest tree)

Server and mod info:
`Paper MC ver: 351 - 1.16.4)
Elite Mobs: 7.2.16`

Let me know if you need any log or information.

**Comment by MagmaGuy** [comment]
Quests are getting rewritten now.
