### ISSUE TITLE
ItemLootShower generates exceptions that fill up server console constantly.

### ISSUE THREAD

**Issue by Nitaray** [MagmaGuy/EliteMobs#48]
![image](https://user-images.githubusercontent.com/38588989/106390895-36229f80-641d-11eb-994b-94f86bcd71d2.png)
**Paper jar**: 1.16.5
**EliteMob ver**: 7.2.16

**Comment by MagmaGuy** [comment]
This bug is caused by disabling the Soulbind enchantment  since that makes bosses no longer drop coins. The latest dev version already fixes this issue, and the changes in the dev version will be made public very soon.

**Comment by Nitaray** [comment]
Thanks for the fast reply!
