### ISSUE TITLE
This Magmaguy and his skull is a little too excessive IMO

### ISSUE THREAD

**Issue by RoboMWM** [MagmaGuy/EliteMobs#5]
https://gist.github.com/RoboMWM/a609448215026845f734d0392fe8e27f

**Comment by MagmaGuy** [comment]
Lowered the speed for ZombieTeamRocket (forgot to fix it before release, the live values were only ever meant for testing purposes) and lowered the amount of calls made to skin servers down to one. I can't exactly make skin servers less bad, so it'll either work or not, but at least it'll only ever error once. Changes will be live as soon as 6.2.1 comes out, or 6.3.0 if you're not getting my dev builds and are getting them from spigot instead.
