### ISSUE TITLE
Self Compiling error 

### ISSUE THREAD

**Issue by QuintenQVD0** [MagmaGuy/EliteMobs#75]
Could not find org.spigotmc:spigot:1.16.1-R0.1-SNAPSHOT

where can i download spigot-1.16.1-R0.1-SNAPSHOT.pom and maven-metadata.xml for spiugot 1.16.1-r0.1?

there is now working maven download link for that.

**Comment by MagmaGuy** [comment]
EliteMobs is using the 1.17 repository.
