### ISSUE TITLE
MOD startup failed？

### ISSUE THREAD

**Issue by Wdam** [MagmaGuy/EliteMobs#76]
This is an error message.
![image](https://user-images.githubusercontent.com/42366809/131085488-ec9b630d-cdfa-4483-81aa-5961a9f462d4.png)

My server core
![image](https://user-images.githubusercontent.com/42366809/131085615-0b8b8991-e13b-405b-b4ae-96dc80aabc34.png)

My Plugins
![image](https://user-images.githubusercontent.com/42366809/131085718-a4f0e0ec-3f43-4cd7-a4ab-bac3fdadd9c7.png)

**Comment by MagmaGuy** [comment]
If you haven't modified this file, delete it and it will be generated again correctly by the plugin!
