### ISSUE TITLE
"Boss Event" After reboot the elite mobs that were named stay with no abilities/drops.

### ISSUE THREAD

**Issue by FrozenBeard** [MagmaGuy/EliteMobs#8]
We have an auto reboot every day.
If an Event Boss Elite mobs are spawned, a reboot happens then they are turned into normal mobs, but look like elite mobs, this confuses players and they complain there are no drops.

**Comment by MagmaGuy** [comment]
That is odd, are you sure that it is going through a clean shutdown and not crashing? You can check for yourself that I do clear entities on shutdown, supposedly the only way to skip it is if the server outright crashes. Also, which version are you using?

**Comment by FrozenBeard** [comment]
Yes its a clean shutdown.

**Comment by MagmaGuy** [comment]
I personally run paper myself and have not experienced this issue so far; I'd say that I'll be looking into it, but if I'm honest I rewrote the shutdown sequence over the past week and based on the test that I did just this second the issue, if it was there in the first place, does not seem to be persisting on my network. I'll be dropping a big rewrite (the one on the non-compile branch) over the next ~48 hours to the dev builds that you can find a link to on my website or on my discord server, you're more than welcome to test those when they come out and tell me if it fixes this specific issue.

**Comment by FrozenBeard** [comment]
I think its more that its just a named mob, named mobs don't despawn. Which means after a reboot there is no saved data to tell EM that specific mob is still named and alive, so its just a randomly named mob in the world unrelated to EM now.

**Comment by MagmaGuy** [comment]
Oh I think I might know what the issue was, if I am right about it then it should be fixed on the rewrite.
