### ISSUE TITLE
Hex color codes support

### ISSUE THREAD

**Issue by andris155** [MagmaGuy/EliteMobs#82]
The plugin currently not supported perfectly the hex colored nick names, and prefixes.

![135728212-04534e05-d4ec-452e-a466-70d52a26dd33](https://user-images.githubusercontent.com/8324198/135899229-4e123e64-11e0-45a3-aab2-325274da4882.png)

Paper 1.17.1 build 300
EliteMobs version 7.3.8

**Comment by MagmaGuy** [comment]
This will only be supported once the spigot api officially supports it.
