### ISSUE TITLE
EliteMobs Prestige bug

### ISSUE THREAD

**Issue by Gapinliant** [MagmaGuy/EliteMobs#84]
If a player obtain the maximum rank of Prestige 10 rank 20,there is no golden block which used to upgrade his Prestige.But he can still click the place where the golden block used to be,and obtain Prestige 11 .And the real problem is,if he reached Prestige 11,he can't use most of the function of EliteMobs,so his efforts were in vain.There are already two palyers obtain prestige 11 and find this bug.I wonder how can I deal with it to save them from this bug

**Comment by eghbalTG** [comment]
![image](https://user-images.githubusercontent.com/22130034/143240476-a7a45431-5eb2-4b73-ba43-a8d4dd849b5e.png)

**Comment by MagmaGuy** [comment]
This should be fixed.
