### ISSUE TITLE
Custom Quests: turnInNPC doesnt work?

### ISSUE THREAD

**Issue by EmanuelMunL** [MagmaGuy/EliteMobs#86]
Im trying to do a custom NPC for Custom Quests, i already make the files for both using the format and put them in the proper folders, but it doesnt work even though the quest file has the 'turnInNPC: sample_NPC.yml' line.
It is not clear which config the NPC file should have in 'interactionType' for giving me the custom quest. 'interactionType: QUEST_GIVER' only show the main quests, and the other options doesnt show the custom quest either.

I appreciate the help and apologize if im mistaken.

Those are the files:

**NPC**: Bobby_quests.yml
```
isEnabled: true
name: Bobby
role: <Simple Missions>
profession: CARTOGRAPHER
location: EliteMobs_adventurers_guild,276.5,91,217.5,0,0
greetings:
- I'm a test npc!
farewell:
- Bye!
dialog:
- Test dialog!
canMove: false
canTalk: true
activationRadius: 3.0
canSleep: false
spawnLocation: em_adventurers_guild,276.42,91.0,218.13,-75.35,41.85
```

**Quest:** custom_quest_1.yml
```
isEnabled: true
customObjectives:
- FETCH_ITEM:filename=rotten_flesh_item.yml:amount=1
customRewards:
- filename=IRON_INGOT:amount=1:chance=1
name: Collect rotten flesh
questLore: '&cGive me that special rotten flesh.'
turnInNPC: Bobby_quests.yml
interactionType: QUEST_GIVER
```
> Here i made a custom object for the objective, all of this is just for testing.

**Comment by MagmaGuy** [comment]
This has been overhauled and resolved.
