### ISSUE TITLE
The plugin creates chests in the air

### ISSUE THREAD

**Issue by valenvaio** [MagmaGuy/EliteMobs#91]
The plugin creates chests in the air. They can only be opened by a player with elite level. Under the admin chest does not open. If you remove the chest through WE then in this place plugin works as if the chest is. How do I disable and remove these chests? Maps where the chests are created are disabled in EM

**Comment by MagmaGuy** [comment]
The only chests EliteMobs has are Treasure Chests. These have to be manually placed, and are usually placed when you install a dungeon. It sounds like you may have installed a dungeon and then removed it from where it was. You will want to reimport the dungeon to reset the files or just delete the entries from the treasure chests. Once that's removed you can manually remove the treasure chests.

**Comment by valenvaio** [comment]
I certainly didn't set up a dungeon at this point. This happened on two different maps. And these maps I mounted and connected while the server is running, and when I went there, there were chests, at the spawning point near the zero coordinates. The chests were hanging in the air.

**Comment by MagmaGuy** [comment]
How many treasure chests do you have in your treasure chests folder?
