### ISSUE TITLE
Soulbound Problem

### ISSUE THREAD

**Issue by JOTAPE2006** [MagmaGuy/EliteMobs#92]
So I'm having a problem that player X is managing to get the Soulbound item that it dropped to player Y

**Comment by TenReeez** [comment]
Yes i've seen that happen as well.  Can pick it up off of the ground

**Comment by MagmaGuy** [comment]
Are the people picking it up admins, because admins may have the soulbind bypass permission

**Comment by TenReeez** [comment]
Its just normal players on my server. Doesnt happen all the time. seems random

**Comment by MagmaGuy** [comment]
This should be fixed.
