### ISSUE TITLE
Catacombs not installed when it is

### ISSUE THREAD

**Issue by TenReeez** [MagmaGuy/EliteMobs#99]
I have installed Catacombs, But when I or players go through the wormhole it says the following in chat (see picture)
Boss works fine, mobs work fine. Just the spam message in chat when players go through the catacombs portal

EliteMObs: 7.3.12

[](url
![Screenshot (849)](https://user-images.githubusercontent.com/76084803/152464640-1e2049c4-a014-4091-8dc4-855b4993ed07.png)
)

**Comment by MagmaGuy** [comment]
Did you /em reload

**Comment by MagmaGuy** [comment]
This should be fixed.
